const fs=require("fs");const {JSDOM}=require("jsdom");
const html=fs.readFileSync("index.html","utf8");
const errors=[];
const dom=new JSDOM(html,{runScripts:"dangerously",pretendToBeVisual:true});
const w=dom.window;
w.addEventListener("error",e=>errors.push("error: "+e.message));
w.HTMLElement.prototype.getBoundingClientRect=()=>({left:10,top:10,width:40,height:40,right:50,bottom:50});
setTimeout(()=>{
  const d=w.document;
  const rooms=d.querySelectorAll("#roomList .room").length;
  const msgs=d.querySelectorAll("#feed .msg").length;
  const reacts=d.querySelectorAll("#feed .react").length;
  d.querySelector("#connectBtn").click();
  const fr=d.querySelector("#feed .react"); if(fr) fr.click();
  d.querySelector("#msgInput").value="gm everyone";
  d.querySelector("#sendBtn").click();
  d.querySelector('[data-tab="board"]').click();
  const board=d.querySelectorAll("#rpane .lb").length;
  console.log("rooms:",rooms,"| messages:",msgs,"| reactions:",reacts,"| leaderboard rows:",board);
  console.log("balance:",d.querySelector("#balTop").textContent.trim());
  console.log("errors:",errors.length?errors:"NONE");
  console.log(errors.length?"FAIL":"RENDER + INTERACTIONS OK");
  w.close(); process.exit(0);
},250);
